-- liquibase formatted sql

-- changeset fsommer:1723154804170-3
CREATE TABLE skima_role
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version     BIGINT                                  NOT NULL,
    name        VARCHAR(255) UNIQUE                     NOT NULL,
    permissions JSONB,
    CONSTRAINT pk_skimarole PRIMARY KEY (id)
);

