-- liquibase formatted sql

-- changeset fsommer:1723198550849-1
CREATE TABLE skill_topic
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version  BIGINT                                  NOT NULL,
    owner_id BIGINT,
    title    VARCHAR(255),
    CONSTRAINT pk_skilltopic PRIMARY KEY (id)
);

-- changeset fsommer:1723198550849-2
CREATE TABLE skill_topic_certifications
(
    skill_topic_id BIGINT NOT NULL,
    certifications VARCHAR(255)
);

-- changeset fsommer:1723198550849-3
CREATE TABLE training_activity
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    version        BIGINT                                  NOT NULL,
    title          VARCHAR(255),
    owner_id       BIGINT,
    skill_topic_id BIGINT,
    CONSTRAINT pk_trainingactivity PRIMARY KEY (id)
);

-- changeset fsommer:1723198550849-4
ALTER TABLE skill_topic
    ADD CONSTRAINT FK_SKILLTOPIC_ON_OWNER FOREIGN KEY (owner_id) REFERENCES skima_user (id);

-- changeset fsommer:1723198550849-5
ALTER TABLE training_activity
    ADD CONSTRAINT FK_TRAININGACTIVITY_ON_OWNER FOREIGN KEY (owner_id) REFERENCES skima_user (id);

-- changeset fsommer:1723198550849-6
ALTER TABLE training_activity
    ADD CONSTRAINT FK_TRAININGACTIVITY_ON_SKILLTOPIC FOREIGN KEY (skill_topic_id) REFERENCES skill_topic (id);

-- changeset fsommer:1723198550849-7
ALTER TABLE skill_topic_certifications
    ADD CONSTRAINT fk_skilltopic_certifications_on_skill_topic FOREIGN KEY (skill_topic_id) REFERENCES skill_topic (id);

-- changeset fsommer:1723462309390-1
ALTER TABLE skill_topic ADD CONSTRAINT skill_topic_title_per_owner_uk UNIQUE (title);


-- changeset fsommer:1723554164508-1
CREATE TABLE training_activity_sub_tasks (training_activity_id BIGINT NOT NULL, sub_tasks VARCHAR(255));

-- changeset fsommer:1723554164508-2
ALTER TABLE training_activity ADD description VARCHAR(1000);
ALTER TABLE training_activity ADD metric VARCHAR(255);
ALTER TABLE training_activity ADD target_amount DOUBLE PRECISION;

-- changeset fsommer:1723554164508-5
ALTER TABLE training_activity ALTER COLUMN  target_amount SET NOT NULL;

-- changeset fsommer:1723554164508-6
ALTER TABLE training_activity_sub_tasks ADD CONSTRAINT fk_trainingactivity_subtasks_on_training_activity FOREIGN KEY (training_activity_id) REFERENCES training_activity (id);

-- changeset fsommer:1723582304964-1
ALTER TABLE training_activity_sub_tasks ALTER COLUMN sub_tasks TYPE VARCHAR(4000) USING (sub_tasks::VARCHAR(4000));
