services:
  postgres:
    container_name: skima-db
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=skillmanager'
      - 'POSTGRES_PASSWORD=local_secret'
      - 'POSTGRES_USER=skima_root'
    ports:
      - '5432:5432'
